spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 310011
    url: jdbc:mysql://localhost:3306/bbs?useSSL=false&serverTimezone=GMT&characterEncoding=UTF-8

  jpa:
    show-sql: true
logging:
  level:
    com.spring.bootjpa: debug
